version: '3.4'

services:

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_store

  adminer:
    image: adminer
    restart: always
    ports:
      - "8079:8080"
