version: '3.4'

services:

  spring-store:
    image: spring-store:1
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_store

  adminer:
    image: adminer
    restart: always
    ports:
      - "8079:8079"