version: '3.1'

services:
  spring-store:
    image: spring-store:0.1
    ports:
      - "8080:8080"
    networks:
      - store-network
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "db_store"
    networks:
      - store-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8079:8080"
    networks:
      - store-network

networks:
  store-network:
    driver: bridge

volumes:
  postgres-data: